version: '3.4'

services:
  saleswebmvc:
    build:
      context: .
      dockerfile: SalesWebMVc/Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - db
    restart: always
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567!@#$%^&C
      MYSQL_DATABASE: saleswebmvcappdb
    ports:
      - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    
volumes:
  mysql-data:

